/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './mail.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '../../../src/mail/mail.component';
const styles_MailComponent:any[] = [i0.styles];
export const RenderType_MailComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_MailComponent,data:{}});
export function View_MailComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'h1',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted((null as any),['Da Mail']))],(null as any),(null as any));
}
export function View_MailComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'mail',([] as any[]),
      (null as any),(null as any),(null as any),View_MailComponent_0,RenderType_MailComponent)),
      i1.ɵdid(49152,(null as any),0,i2.MailComponent,([] as any[]),(null as any),(null as any))],
      (null as any),(null as any));
}
export const MailComponentNgFactory:i1.ComponentFactory<i2.MailComponent> = i1.ɵccf('mail',
    i2.MailComponent,View_MailComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRTovUHJvamVrdGUvWUFDaGF0L3dlYmNsaWVudC9zcmMvbWFpbC9tYWlsLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9FOi9Qcm9qZWt0ZS9ZQUNoYXQvd2ViY2xpZW50L3NyYy9tYWlsL21haWwuY29tcG9uZW50LnRzIiwibmc6Ly8vRTovUHJvamVrdGUvWUFDaGF0L3dlYmNsaWVudC9zcmMvbWFpbC9tYWlsLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRTovUHJvamVrdGUvWUFDaGF0L3dlYmNsaWVudC9zcmMvbWFpbC9tYWlsLmNvbXBvbmVudC50cy5NYWlsQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGgxPkRhIE1haWw8L2gxPiIsIjxtYWlsPjwvbWFpbD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQSx3RUFBSTthQUFBOzs7b0JDQUo7TUFBQTthQUFBOzs7OyJ9
