/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './mail.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '../../../src/mail/mail.component';
const styles_MailComponent:any[] = [i0.styles];
export const RenderType_MailComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_MailComponent,data:{}});
export function View_MailComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'h1',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted((null as any),['Da Mail']))],(null as any),(null as any));
}
export function View_MailComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'mail',([] as any[]),
      (null as any),(null as any),(null as any),View_MailComponent_0,RenderType_MailComponent)),
      i1.ɵdid(49152,(null as any),0,i2.MailComponent,([] as any[]),(null as any),(null as any))],
      (null as any),(null as any));
}
export const MailComponentNgFactory:i1.ComponentFactory<i2.MailComponent> = i1.ɵccf('mail',
    i2.MailComponent,View_MailComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvUHJlc2NoZXJGYS9Qcm9qZWt0ZS9ZQUNoYXQvd2ViY2xpZW50L3NyYy9tYWlsL21haWwuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL1ByZXNjaGVyRmEvUHJvamVrdGUvWUFDaGF0L3dlYmNsaWVudC9zcmMvbWFpbC9tYWlsLmNvbXBvbmVudC50cyIsIm5nOi8vL0M6L1VzZXJzL1ByZXNjaGVyRmEvUHJvamVrdGUvWUFDaGF0L3dlYmNsaWVudC9zcmMvbWFpbC9tYWlsLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvUHJlc2NoZXJGYS9Qcm9qZWt0ZS9ZQUNoYXQvd2ViY2xpZW50L3NyYy9tYWlsL21haWwuY29tcG9uZW50LnRzLk1haWxDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8aDE+RGEgTWFpbDwvaDE+IiwiPG1haWw+PC9tYWlsPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7OztvQkNBQTtNQUFBLHdFQUFJO2FBQUE7OztvQkNBSjtNQUFBO2FBQUE7Ozs7In0=
