/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../src/app.routing.module';
import * as i2 from './login.component.ngfactory';
import * as i3 from './chat/chat.component.ngfactory';
import * as i4 from './mail/mail.component.ngfactory';
import * as i5 from './not-found.component.ngfactory';
import * as i6 from '@angular/router';
import * as i7 from '@angular/common';
import * as i8 from '../../src/login.component';
import * as i9 from '../../src/chat/chat.component';
import * as i10 from '../../src/mail/mail.component';
import * as i11 from '../../src/not-found.component';
export const AppRoutingModuleNgFactory:i0.NgModuleFactory<i1.AppRoutingModule> = i0.ɵcmf(i1.AppRoutingModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.LoginComponentNgFactory,i3.ChatComponentNgFactory,i4.MailComponentNgFactory,
              i5.NotFoundComponentNgFactory]],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),
          i0.ɵmpd(5120,i6.ActivatedRoute,i6.ɵf,[i6.Router]),i0.ɵmpd(4608,i6.NoPreloading,
              i6.NoPreloading,([] as any[])),i0.ɵmpd(6144,i6.PreloadingStrategy,(null as any),
              [i6.NoPreloading]),i0.ɵmpd(135680,i6.RouterPreloader,i6.RouterPreloader,
              [i6.Router,i0.NgModuleFactoryLoader,i0.Compiler,i0.Injector,i6.PreloadingStrategy]),
          i0.ɵmpd(4608,i6.PreloadAllModules,i6.PreloadAllModules,([] as any[])),i0.ɵmpd(5120,
              i0.NgProbeToken,() => {
                return [i6.ɵb()];
              },([] as any[])),i0.ɵmpd(4608,i6.ɵg,i6.ɵg,[i0.Injector]),i0.ɵmpd(5120,
              i0.APP_INITIALIZER,(p0_0:any) => {
                return [i6.ɵh(p0_0)];
              },[i6.ɵg]),i0.ɵmpd(5120,i6.ROUTER_INITIALIZER,i6.ɵi,[i6.ɵg]),i0.ɵmpd(5120,
              i0.APP_BOOTSTRAP_LISTENER,(p0_0:any) => {
                return [p0_0];
              },[i6.ROUTER_INITIALIZER]),i0.ɵmpd(1024,i6.ɵa,i6.ɵd,[[3,i6.Router]]),
          i0.ɵmpd(512,i6.UrlSerializer,i6.DefaultUrlSerializer,([] as any[])),i0.ɵmpd(512,
              i6.ChildrenOutletContexts,i6.ChildrenOutletContexts,([] as any[])),i0.ɵmpd(256,
              i6.ROUTER_CONFIGURATION,{enableTracing:true},([] as any[])),i0.ɵmpd(1024,
              i7.LocationStrategy,i6.ɵc,[i7.PlatformLocation,[2,i7.APP_BASE_HREF],
                  i6.ROUTER_CONFIGURATION]),i0.ɵmpd(512,i7.Location,i7.Location,[i7.LocationStrategy]),
          i0.ɵmpd(512,i0.NgModuleFactoryLoader,i0.SystemJsNgModuleLoader,[i0.Compiler,
              [2,i0.SystemJsNgModuleLoaderConfig]]),i0.ɵmpd(1024,i6.ROUTES,() => {
            return [[{path:'',redirectTo:'login',pathMatch:'full'},{path:'login',component:i8.LoginComponent},
                {path:'chat',component:i9.ChatComponent},{path:'mail',component:i10.MailComponent},
                {path:'**',component:i11.NotFoundComponent}]];
          },([] as any[])),i0.ɵmpd(1024,i6.Router,i6.ɵe,[i0.ApplicationRef,i6.UrlSerializer,
              i6.ChildrenOutletContexts,i7.Location,i0.Injector,i0.NgModuleFactoryLoader,
              i0.Compiler,i6.ROUTES,i6.ROUTER_CONFIGURATION,[2,i6.UrlHandlingStrategy],
              [2,i6.RouteReuseStrategy]]),i0.ɵmpd(512,i6.RouterModule,i6.RouterModule,
              [[2,i6.ɵa],[2,i6.Router]]),i0.ɵmpd(512,i1.AppRoutingModule,i1.AppRoutingModule,
              ([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRTovUHJvamVrdGUvWUFDaGF0L3dlYmNsaWVudC9zcmMvYXBwLnJvdXRpbmcubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0U6L1Byb2pla3RlL1lBQ2hhdC93ZWJjbGllbnQvc3JjL2FwcC5yb3V0aW5nLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
