/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.login[_ngcontent-%COMP%]   input[_ngcontent-%COMP%] {\r\n    border: 0;\r\n    font-size: 1em;\r\n    display: block;\r\n    padding: 10px;\r\n    text-align: center;\r\n    width: 100%;\r\n}\r\n\r\n.login[_ngcontent-%COMP%]   label[_ngcontent-%COMP%] {\r\n    border: 0;\r\n    font-size: 1em;\r\n    display: block;\r\n    padding: 10px;\r\n    text-align: center;\r\n    width: 100%;\r\n}\r\n\r\n.login[_ngcontent-%COMP%]   h1[_ngcontent-%COMP%] {\r\n    padding-top: 30px;\r\n    padding-bottom: 30px;\r\n    text-align: center;\r\n}\r\n\r\n.login[_ngcontent-%COMP%]   button[_ngcontent-%COMP%] {\r\n    font-size: 1em;\r\n    background: rgb(255, 153, 0);\r\n    border: none;\r\n    display: block;\r\n    padding: 10px;\r\n    margin-top: 20px;\r\n    width: 100%;\r\n}\r\n\r\n.login[_ngcontent-%COMP%]    > div[_ngcontent-%COMP%]    > div[_ngcontent-%COMP%] {\r\n    padding-bottom: 10px;\r\n    padding-left: 20px;\r\n    padding-right: 20px;\r\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRTovUHJvamVrdGUvWUFDaGF0L3dlYmNsaWVudC9zcmMvbG9naW4uY29tcG9uZW50LmNzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9FOi9Qcm9qZWt0ZS9ZQUNoYXQvd2ViY2xpZW50L3NyYy9sb2dpbi5jb21wb25lbnQuY3NzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
