/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.login[_ngcontent-%COMP%]   input[_ngcontent-%COMP%] {\n    border: 0;\n    font-size: 1em;\n    display: block;\n    padding: 10px;\n    text-align: center;\n    width: 100%;\n}\n\n.login[_ngcontent-%COMP%]   label[_ngcontent-%COMP%] {\n    border: 0;\n    font-size: 1em;\n    display: block;\n    padding: 10px;\n    text-align: center;\n    width: 100%;\n}\n\n.login[_ngcontent-%COMP%]   h1[_ngcontent-%COMP%] {\n    padding-top: 30px;\n    padding-bottom: 30px;\n    text-align: center;\n}\n\n.login[_ngcontent-%COMP%]   button[_ngcontent-%COMP%] {\n    font-size: 1em;\n    background: rgb(255, 153, 0);\n    border: none;\n    display: block;\n    padding: 10px;\n    margin-top: 20px;\n    width: 100%;\n}\n\n.login[_ngcontent-%COMP%]    > div[_ngcontent-%COMP%]    > div[_ngcontent-%COMP%] {\n    padding-bottom: 10px;\n    padding-left: 20px;\n    padding-right: 20px;\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvUHJlc2NoZXJGYS9Qcm9qZWt0ZS9ZQUNoYXQvd2ViY2xpZW50L3NyYy9sb2dpbi5jb21wb25lbnQuY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL1ByZXNjaGVyRmEvUHJvamVrdGUvWUFDaGF0L3dlYmNsaWVudC9zcmMvbG9naW4uY29tcG9uZW50LmNzcyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
