/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './login.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '../../src/login.component';
const styles_LoginComponent:any[] = [i0.styles];
export const RenderType_LoginComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_LoginComponent,data:{}});
export function View_LoginComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'h1',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted((null as any),['',''])),(_l()(),i1.ɵted((null as any),['\n'])),(_l()(),
      i1.ɵeld(0,(null as any),(null as any),24,'div',([] as any[]),(null as any),(null as any),
          (null as any),(null as any),(null as any))),(_l()(),i1.ɵted((null as any),
      ['\n    '])),(_l()(),i1.ɵeld(0,(null as any),(null as any),6,'div',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted((null as any),['\n        '])),(_l()(),i1.ɵeld(0,(null as any),(null as any),
      1,'label',([] as any[]),(null as any),(null as any),(null as any),(null as any),
      (null as any))),(_l()(),i1.ɵted((null as any),['Username'])),(_l()(),i1.ɵted((null as any),
      ['\n        '])),(_l()(),i1.ɵeld(0,(null as any),(null as any),0,'input',[['maxlength',
      '255'],['placeholder','Please enter a username in here!']],(null as any),(null as any),
      (null as any),(null as any),(null as any))),(_l()(),i1.ɵted((null as any),['\n    '])),
      (_l()(),i1.ɵted((null as any),['\n    '])),(_l()(),i1.ɵeld(0,(null as any),(null as any),
          6,'div',([] as any[]),(null as any),(null as any),(null as any),(null as any),
          (null as any))),(_l()(),i1.ɵted((null as any),['\n        '])),(_l()(),i1.ɵeld(0,
          (null as any),(null as any),1,'label',([] as any[]),(null as any),(null as any),
          (null as any),(null as any),(null as any))),(_l()(),i1.ɵted((null as any),
          ['Password'])),(_l()(),i1.ɵted((null as any),['\n        '])),(_l()(),i1.ɵeld(0,
          (null as any),(null as any),0,'input',[['maxlength','255'],['placeholder',
              'Please enter a passwort in here!'],['type','password']],(null as any),
          (null as any),(null as any),(null as any),(null as any))),(_l()(),i1.ɵted((null as any),
          ['\n    '])),(_l()(),i1.ɵted((null as any),['\n    '])),(_l()(),i1.ɵeld(0,
          (null as any),(null as any),5,'div',([] as any[]),(null as any),(null as any),
          (null as any),(null as any),(null as any))),(_l()(),i1.ɵted((null as any),
          ['\n        '])),(_l()(),i1.ɵeld(0,(null as any),(null as any),2,'button',
          ([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i1.ɵeld(0,(null as any),(null as any),1,'span',([] as any[]),(null as any),
          (null as any),(null as any),(null as any),(null as any))),(_l()(),i1.ɵted((null as any),
          ['Login'])),(_l()(),i1.ɵted((null as any),['\n    '])),(_l()(),i1.ɵted((null as any),
          ['\n']))],(null as any),(_ck,_v) => {
    var _co:i2.LoginComponent = _v.component;
    const currVal_0:any = _co.title;
    _ck(_v,1,0,currVal_0);
  });
}
export function View_LoginComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'login',([] as any[]),
      (null as any),(null as any),(null as any),View_LoginComponent_0,RenderType_LoginComponent)),
      i1.ɵdid(49152,(null as any),0,i2.LoginComponent,([] as any[]),(null as any),
          (null as any))],(null as any),(null as any));
}
export const LoginComponentNgFactory:i1.ComponentFactory<i2.LoginComponent> = i1.ɵccf('login',
    i2.LoginComponent,View_LoginComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRTovUHJvamVrdGUvWUFDaGF0L3dlYmNsaWVudC9zcmMvbG9naW4uY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0U6L1Byb2pla3RlL1lBQ2hhdC93ZWJjbGllbnQvc3JjL2xvZ2luLmNvbXBvbmVudC50cyIsIm5nOi8vL0U6L1Byb2pla3RlL1lBQ2hhdC93ZWJjbGllbnQvc3JjL2xvZ2luLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRTovUHJvamVrdGUvWUFDaGF0L3dlYmNsaWVudC9zcmMvbG9naW4uY29tcG9uZW50LnRzLkxvZ2luQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGgxPnt7IHRpdGxlIH19PC9oMT5cclxuPGRpdj5cclxuICAgIDxkaXY+XHJcbiAgICAgICAgPGxhYmVsPlVzZXJuYW1lPC9sYWJlbD5cclxuICAgICAgICA8aW5wdXQgbWF4bGVuZ3RoPVwiMjU1XCIgcGxhY2Vob2xkZXI9XCJQbGVhc2UgZW50ZXIgYSB1c2VybmFtZSBpbiBoZXJlIVwiIC8+XHJcbiAgICA8L2Rpdj5cclxuICAgIDxkaXY+XHJcbiAgICAgICAgPGxhYmVsPlBhc3N3b3JkPC9sYWJlbD5cclxuICAgICAgICA8aW5wdXQgdHlwZT1cInBhc3N3b3JkXCIgbWF4bGVuZ3RoPVwiMjU1XCIgcGxhY2Vob2xkZXI9XCJQbGVhc2UgZW50ZXIgYSBwYXNzd29ydCBpbiBoZXJlIVwiIC8+XHJcbiAgICA8L2Rpdj5cclxuICAgIDxkaXY+XHJcbiAgICAgICAgPGJ1dHRvbj48c3Bhbj5Mb2dpbjwvc3Bhbj48L2J1dHRvbj5cclxuICAgIDwvZGl2PlxyXG48L2Rpdj4iLCI8bG9naW4+PC9sb2dpbj4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQSx3RUFBSTthQUFBLHlCQUFnQix1Q0FDcEI7YUFBQTtVQUFBLDRDQUFLO01BQUEsYUFDRDtNQUFBLHdFQUFLO2FBQUEsZ0NBQ0Q7TUFBQTtNQUFBLGdCQUFPLDZDQUFnQjtNQUFBLGlCQUN2QjtNQUFBO01BQUEsNENBQXdFO01BQ3RFLDJDQUNOO1VBQUE7VUFBQSxnQkFBSywrQ0FDRDtVQUFBO1VBQUEsNENBQU87VUFBQSxlQUFnQiwrQ0FDdkI7VUFBQTtjQUFBO1VBQUEsMERBQXdGO1VBQUEsYUFDdEYsMkNBQ047VUFBQTtVQUFBLDRDQUFLO1VBQUEsaUJBQ0Q7VUFBQTtNQUFRO1VBQUEsMERBQU07VUFBQSxZQUFxQiwyQ0FDakM7VUFBQTs7SUFaTjtJQUFBOzs7O29CQ0FKO01BQUE7YUFBQTtVQUFBOzs7In0=
