/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './mail.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '../../src/mail.component';
const styles_MailComponent:any[] = [i0.styles];
export const RenderType_MailComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_MailComponent,data:{}});
export function View_MailComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'h1',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted((null as any),['Da Mail']))],(null as any),(null as any));
}
export function View_MailComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'mail',([] as any[]),
      (null as any),(null as any),(null as any),View_MailComponent_0,RenderType_MailComponent)),
      i1.ɵdid(49152,(null as any),0,i2.MailComponent,([] as any[]),(null as any),(null as any))],
      (null as any),(null as any));
}
export const MailComponentNgFactory:i1.ComponentFactory<i2.MailComponent> = i1.ɵccf('mail',
    i2.MailComponent,View_MailComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRTovUHJvamVrdGUvWUFDaGF0L3dlYmNsaWVudC9zcmMvbWFpbC5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRTovUHJvamVrdGUvWUFDaGF0L3dlYmNsaWVudC9zcmMvbWFpbC5jb21wb25lbnQudHMiLCJuZzovLy9FOi9Qcm9qZWt0ZS9ZQUNoYXQvd2ViY2xpZW50L3NyYy9tYWlsLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRTovUHJvamVrdGUvWUFDaGF0L3dlYmNsaWVudC9zcmMvbWFpbC5jb21wb25lbnQudHMuTWFpbENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxoMT5EYSBNYWlsPC9oMT4iLCI8bWFpbD48L21haWw+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7O29CQ0FBO01BQUEsd0VBQUk7YUFBQTs7O29CQ0FKO01BQUE7YUFBQTs7OzsifQ==
