/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './not-found.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '../../src/not-found.component';
const styles_NotFoundComponent:any[] = [i0.styles];
export const RenderType_NotFoundComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_NotFoundComponent,data:{}});
export function View_NotFoundComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'h1',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted((null as any),['','']))],(null as any),(_ck,_v) => {
    var _co:i2.NotFoundComponent = _v.component;
    const currVal_0:any = _co.title;
    _ck(_v,1,0,currVal_0);
  });
}
export function View_NotFoundComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'not-found',([] as any[]),
      (null as any),(null as any),(null as any),View_NotFoundComponent_0,RenderType_NotFoundComponent)),
      i1.ɵdid(49152,(null as any),0,i2.NotFoundComponent,([] as any[]),(null as any),
          (null as any))],(null as any),(null as any));
}
export const NotFoundComponentNgFactory:i1.ComponentFactory<i2.NotFoundComponent> = i1.ɵccf('not-found',
    i2.NotFoundComponent,View_NotFoundComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRTovUHJvamVrdGUvWUFDaGF0L3dlYmNsaWVudC9zcmMvbm90LWZvdW5kLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9FOi9Qcm9qZWt0ZS9ZQUNoYXQvd2ViY2xpZW50L3NyYy9ub3QtZm91bmQuY29tcG9uZW50LnRzIiwibmc6Ly8vRTovUHJvamVrdGUvWUFDaGF0L3dlYmNsaWVudC9zcmMvbm90LWZvdW5kLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRTovUHJvamVrdGUvWUFDaGF0L3dlYmNsaWVudC9zcmMvbm90LWZvdW5kLmNvbXBvbmVudC50cy5Ob3RGb3VuZENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxoMT57eyB0aXRsZSB9fTwvaDE+IiwiPG5vdC1mb3VuZD48L25vdC1mb3VuZD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQSx3RUFBSTthQUFBOztJQUFBO0lBQUE7Ozs7b0JDQUo7TUFBQTthQUFBO1VBQUE7OzsifQ==
