/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './not-found.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '../../src/not-found.component';
const styles_NotFoundComponent:any[] = [i0.styles];
export const RenderType_NotFoundComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_NotFoundComponent,data:{}});
export function View_NotFoundComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'h1',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted((null as any),['','']))],(null as any),(_ck,_v) => {
    var _co:i2.NotFoundComponent = _v.component;
    const currVal_0:any = _co.title;
    _ck(_v,1,0,currVal_0);
  });
}
export function View_NotFoundComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'not-found',([] as any[]),
      (null as any),(null as any),(null as any),View_NotFoundComponent_0,RenderType_NotFoundComponent)),
      i1.ɵdid(49152,(null as any),0,i2.NotFoundComponent,([] as any[]),(null as any),
          (null as any))],(null as any),(null as any));
}
export const NotFoundComponentNgFactory:i1.ComponentFactory<i2.NotFoundComponent> = i1.ɵccf('not-found',
    i2.NotFoundComponent,View_NotFoundComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvUHJlc2NoZXJGYS9Qcm9qZWt0ZS9ZQUNoYXQvd2ViY2xpZW50L3NyYy9ub3QtZm91bmQuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL1ByZXNjaGVyRmEvUHJvamVrdGUvWUFDaGF0L3dlYmNsaWVudC9zcmMvbm90LWZvdW5kLmNvbXBvbmVudC50cyIsIm5nOi8vL0M6L1VzZXJzL1ByZXNjaGVyRmEvUHJvamVrdGUvWUFDaGF0L3dlYmNsaWVudC9zcmMvbm90LWZvdW5kLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvUHJlc2NoZXJGYS9Qcm9qZWt0ZS9ZQUNoYXQvd2ViY2xpZW50L3NyYy9ub3QtZm91bmQuY29tcG9uZW50LnRzLk5vdEZvdW5kQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGgxPnt7IHRpdGxlIH19PC9oMT4iLCI8bm90LWZvdW5kPjwvbm90LWZvdW5kPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7OztvQkNBQTtNQUFBLHdFQUFJO2FBQUE7O0lBQUE7SUFBQTs7OztvQkNBSjtNQUFBO2FBQUE7VUFBQTs7OyJ9
