/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.chat-actionbar[_ngcontent-%COMP%] {\n    background: rgb(0, 51, 102);\n    position: absolute;\n    bottom: 0;\n    width: 100%;\n    padding: 3px 0px 3px 0px;\n    z-index: 30;\n}\n\n.chat-actionbar[_ngcontent-%COMP%]   .input-message[_ngcontent-%COMP%] {\n    border: none;\n    width: calc(85% - 3px);\n    display: block;\n    float: left;\n}\n\n.chat-actionbar[_ngcontent-%COMP%]   .input-message[_ngcontent-%COMP%]   input[_ngcontent-%COMP%] {\n    border: 0;\n    font-size: 1em;\n    width: 100%;\n    display: block;\n    padding: 10px;\n}\n\n.chat-actionbar[_ngcontent-%COMP%]   .btn-send[_ngcontent-%COMP%] {\n    font-size: 1em;\n    width: 15%;\n    background: rgb(255, 153, 0);\n    border: none;\n    display: block;\n    float: left;\n}\n\n.chat-actionbar[_ngcontent-%COMP%]   .btn-send[_ngcontent-%COMP%]   button[_ngcontent-%COMP%] {\n    font-size: 1em;\n    width: 100%;\n    background: rgb(255, 153, 0);\n    border: none;\n    display: block;\n    padding: 10px;\n}\n\n.chat-actionbar[_ngcontent-%COMP%]   .btn-send[_ngcontent-%COMP%]   button[_ngcontent-%COMP%]:active {\n    background: rgb(225, 123, 0);\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvUHJlc2NoZXJGYS9Qcm9qZWt0ZS9ZQUNoYXQvd2ViY2xpZW50L3NyYy9jaGF0L2NoYXQtYWN0aW9uYmFyLmNvbXBvbmVudC5jc3Muc2hpbS5uZ3N0eWxlLnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovVXNlcnMvUHJlc2NoZXJGYS9Qcm9qZWt0ZS9ZQUNoYXQvd2ViY2xpZW50L3NyYy9jaGF0L2NoYXQtYWN0aW9uYmFyLmNvbXBvbmVudC5jc3MiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7OyJ9
