/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './chat-messages.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '@angular/common';
import * as i3 from '../../../src/chat/chat-messages.component';
import * as i4 from '../../../src/chat/chat.service';
const styles_ChatMessagesComponent:any[] = [i0.styles];
export const RenderType_ChatMessagesComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_ChatMessagesComponent,data:{}});
function View_ChatMessagesComponent_1(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),3,'li',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),i1.ɵdid(278528,
      (null as any),0,i2.NgClass,[i1.IterableDiffers,i1.KeyValueDiffers,i1.ElementRef,
          i1.Renderer],{ngClass:[0,'ngClass']},(null as any)),i1.ɵpod({'bold':0}),
      (_l()(),i1.ɵted((null as any),['\n                ',' [',']: ','\n            ']))],
      (_ck,_v) => {
        var _co:any = _v.component;
        const currVal_0:any = _ck(_v,2,0,(_v.context.$implicit.userid === _co.chatService.getChat().getCurrentUserId()));
        _ck(_v,1,0,currVal_0);
      },(_ck,_v) => {
        const currVal_1:any = _v.context.$implicit.username;
        const currVal_2:any = _v.context.$implicit.userid;
        const currVal_3:any = _v.context.$implicit.msg;
        _ck(_v,3,0,currVal_1,currVal_2,currVal_3);
      });
}
export function View_ChatMessagesComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[i1.ɵqud(402653184,1,{chatMessagesElementRef:0}),(_l()(),i1.ɵeld(0,
      [[1,0],['chatMessages',1]],(null as any),10,'div',[['class','chat-messages container']],
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted((null as any),['\n    '])),(_l()(),i1.ɵeld(0,(null as any),(null as any),
      7,'div',([] as any[]),(null as any),(null as any),(null as any),(null as any),
      (null as any))),(_l()(),i1.ɵted((null as any),['\n        '])),(_l()(),i1.ɵeld(0,
      (null as any),(null as any),4,'ul',([] as any[]),(null as any),(null as any),
      (null as any),(null as any),(null as any))),(_l()(),i1.ɵted((null as any),['\n            '])),
      (_l()(),i1.ɵand(16777216,(null as any),(null as any),1,(null as any),View_ChatMessagesComponent_1)),
      i1.ɵdid(802816,(null as any),0,i2.NgForOf,[i1.ViewContainerRef,i1.TemplateRef,
          i1.IterableDiffers],{ngForOf:[0,'ngForOf']},(null as any)),(_l()(),i1.ɵted((null as any),
          ['\n        '])),(_l()(),i1.ɵted((null as any),['\n    '])),(_l()(),i1.ɵted((null as any),
          ['\n']))],(_ck,_v) => {
    var _co:i3.ChatMessagesComponent = _v.component;
    const currVal_0:any = _co.chatService.getChat().messages;
    _ck(_v,8,0,currVal_0);
  },(null as any));
}
export function View_ChatMessagesComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'chat-messages',
      ([] as any[]),(null as any),(null as any),(null as any),View_ChatMessagesComponent_0,
      RenderType_ChatMessagesComponent)),i1.ɵdid(8503296,(null as any),0,i3.ChatMessagesComponent,
      [i4.ChatService],(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const ChatMessagesComponentNgFactory:i1.ComponentFactory<i3.ChatMessagesComponent> = i1.ɵccf('chat-messages',
    i3.ChatMessagesComponent,View_ChatMessagesComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvUHJlc2NoZXJGYS9Qcm9qZWt0ZS9ZQUNoYXQvd2ViY2xpZW50L3NyYy9jaGF0L2NoYXQtbWVzc2FnZXMuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL1ByZXNjaGVyRmEvUHJvamVrdGUvWUFDaGF0L3dlYmNsaWVudC9zcmMvY2hhdC9jaGF0LW1lc3NhZ2VzLmNvbXBvbmVudC50cyIsIm5nOi8vL0M6L1VzZXJzL1ByZXNjaGVyRmEvUHJvamVrdGUvWUFDaGF0L3dlYmNsaWVudC9zcmMvY2hhdC9jaGF0LW1lc3NhZ2VzLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvUHJlc2NoZXJGYS9Qcm9qZWt0ZS9ZQUNoYXQvd2ViY2xpZW50L3NyYy9jaGF0L2NoYXQtbWVzc2FnZXMuY29tcG9uZW50LnRzLkNoYXRNZXNzYWdlc0NvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxkaXYgI2NoYXRNZXNzYWdlcyBjbGFzcz1cImNoYXQtbWVzc2FnZXMgY29udGFpbmVyXCI+XG4gICAgPGRpdj5cbiAgICAgICAgPHVsPlxuICAgICAgICAgICAgPGxpIFxuICAgICAgICAgICAgICAgICpuZ0Zvcj1cImxldCBtZXNzYWdlIG9mIGNoYXRTZXJ2aWNlLmdldENoYXQoKS5tZXNzYWdlc1wiIFxuICAgICAgICAgICAgICAgIFtuZ0NsYXNzXT1cInsgJ2JvbGQnOiBtZXNzYWdlLnVzZXJpZCA9PT0gY2hhdFNlcnZpY2UuZ2V0Q2hhdCgpLmdldEN1cnJlbnRVc2VySWQoKSB9XCI+XG4gICAgICAgICAgICAgICAge3ttZXNzYWdlLnVzZXJuYW1lfX0gW3t7IG1lc3NhZ2UudXNlcmlkIH19XToge3sgbWVzc2FnZS5tc2cgfX1cbiAgICAgICAgICAgIDwvbGk+XG4gICAgICAgIDwvdWw+XG4gICAgPC9kaXY+XG48L2Rpdj4iLCI8Y2hhdC1tZXNzYWdlcz48L2NoYXQtbWVzc2FnZXM+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7b0JDR1k7TUFBQSwrRUFBQTtNQUFBO3FCQUFBLGdEQUVJO01BQW9GOzs7UUFBcEY7UUFGSixXQUVJLFNBRko7O1FBRXdGO1FBQUE7UUFBQTtRQUFBOzs7O29FQUxwRztNQUFBO01BQUEsd0VBQW1EO2FBQUEsNEJBQy9DO01BQUE7TUFBQSxnQkFBSywrQ0FDRDtNQUFBO01BQUEsNENBQUk7TUFDQTthQUFBOzRCQUFBLHlDQUlLO1VBQUEsaUJBQ0osMkNBQ0g7VUFBQTs7SUFMTTtJQURKLFdBQ0ksU0FESjs7OztvQkNIWjtNQUFBO3NDQUFBLFVBQUE7TUFBQTtJQUFBOzs7OyJ9
