/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './chat-actionbar.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '../../../src/chat/chat-actionbar.component';
const styles_ChatActionbarComponent:any[] = [i0.styles];
export const RenderType_ChatActionbarComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_ChatActionbarComponent,data:{}});
export function View_ChatActionbarComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),11,'form',[['action',
      ''],['class','chat-actionbar container']],(null as any),(null as any),(null as any),
      (null as any),(null as any))),(_l()(),i1.ɵted((null as any),['\n    '])),(_l()(),
      i1.ɵeld(0,(null as any),(null as any),8,'div',[['class','row']],(null as any),
          (null as any),(null as any),(null as any),(null as any))),(_l()(),i1.ɵted((null as any),
      ['\n        '])),(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'div',[['class',
      'column input-message'],['id','divMessage']],(null as any),(null as any),(null as any),
      (null as any),(null as any))),(_l()(),i1.ɵeld(0,(null as any),(null as any),
      0,'input',[['autocomplete','off'],['id','message']],(null as any),(null as any),
      (null as any),(null as any),(null as any))),(_l()(),i1.ɵted((null as any),['\n        '])),
      (_l()(),i1.ɵeld(0,(null as any),(null as any),2,'div',[['class','column btn-send'],
          ['id','divSend']],(null as any),(null as any),(null as any),(null as any),
          (null as any))),(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'button',
          ([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i1.ɵted((null as any),['Send'])),(_l()(),i1.ɵted((null as any),['\n    '])),
      (_l()(),i1.ɵted((null as any),['\n']))],(null as any),(null as any));
}
export function View_ChatActionbarComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'chat-actionbar',
      ([] as any[]),(null as any),(null as any),(null as any),View_ChatActionbarComponent_0,
      RenderType_ChatActionbarComponent)),i1.ɵdid(49152,(null as any),0,i2.ChatActionbarComponent,
      ([] as any[]),(null as any),(null as any))],(null as any),(null as any));
}
export const ChatActionbarComponentNgFactory:i1.ComponentFactory<i2.ChatActionbarComponent> = i1.ɵccf('chat-actionbar',
    i2.ChatActionbarComponent,View_ChatActionbarComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRTovUHJvamVrdGUvWUFDaGF0L3dlYmNsaWVudC9zcmMvY2hhdC9jaGF0LWFjdGlvbmJhci5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRTovUHJvamVrdGUvWUFDaGF0L3dlYmNsaWVudC9zcmMvY2hhdC9jaGF0LWFjdGlvbmJhci5jb21wb25lbnQudHMiLCJuZzovLy9FOi9Qcm9qZWt0ZS9ZQUNoYXQvd2ViY2xpZW50L3NyYy9jaGF0L2NoYXQtYWN0aW9uYmFyLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRTovUHJvamVrdGUvWUFDaGF0L3dlYmNsaWVudC9zcmMvY2hhdC9jaGF0LWFjdGlvbmJhci5jb21wb25lbnQudHMuQ2hhdEFjdGlvbmJhckNvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxmb3JtIGFjdGlvbj1cIlwiIGNsYXNzPVwiY2hhdC1hY3Rpb25iYXIgY29udGFpbmVyXCI+XHJcbiAgICA8ZGl2IGNsYXNzPVwicm93XCI+XHJcbiAgICAgICAgPGRpdiBpZD1cImRpdk1lc3NhZ2VcIiBjbGFzcz1cImNvbHVtbiBpbnB1dC1tZXNzYWdlXCI+PGlucHV0IGlkPVwibWVzc2FnZVwiIGF1dG9jb21wbGV0ZT1cIm9mZlwiIC8+PC9kaXY+XHJcbiAgICAgICAgPGRpdiBpZD1cImRpdlNlbmRcIiBjbGFzcz1cImNvbHVtbiBidG4tc2VuZFwiPjxidXR0b24+U2VuZDwvYnV0dG9uPjwvZGl2PlxyXG4gICAgPC9kaXY+XHJcbjwvZm9ybT4iLCI8Y2hhdC1hY3Rpb25iYXI+PC9jaGF0LWFjdGlvbmJhcj4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQTtNQUFBLDhCQUFpRCwyQ0FDN0M7YUFBQTtVQUFBLDBEQUFpQjtNQUFBLGlCQUNiO01BQUE7TUFBQSw4QkFBa0Q7TUFBQTtNQUFBLDRDQUErQztNQUNqRztVQUFBO1VBQUEsZ0JBQTBDO1VBQUE7TUFBUSx5Q0FBbUI7TUFDbkU7OztvQkNKVjtNQUFBO3VDQUFBLFVBQUE7TUFBQTs7OyJ9
