/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './chat.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '../../../src/chat/chat.component';
const styles_ChatComponent:any[] = [i0.styles];
export const RenderType_ChatComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_ChatComponent,data:{}});
export function View_ChatComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'h1',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted((null as any),['Da Chat']))],(null as any),(null as any));
}
export function View_ChatComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'chat',([] as any[]),
      (null as any),(null as any),(null as any),View_ChatComponent_0,RenderType_ChatComponent)),
      i1.ɵdid(49152,(null as any),0,i2.ChatComponent,([] as any[]),(null as any),(null as any))],
      (null as any),(null as any));
}
export const ChatComponentNgFactory:i1.ComponentFactory<i2.ChatComponent> = i1.ɵccf('chat',
    i2.ChatComponent,View_ChatComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRTovUHJvamVrdGUvWUFDaGF0L3dlYmNsaWVudC9zcmMvY2hhdC9jaGF0LmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9FOi9Qcm9qZWt0ZS9ZQUNoYXQvd2ViY2xpZW50L3NyYy9jaGF0L2NoYXQuY29tcG9uZW50LnRzIiwibmc6Ly8vRTovUHJvamVrdGUvWUFDaGF0L3dlYmNsaWVudC9zcmMvY2hhdC9jaGF0LmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRTovUHJvamVrdGUvWUFDaGF0L3dlYmNsaWVudC9zcmMvY2hhdC9jaGF0LmNvbXBvbmVudC50cy5DaGF0Q29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGgxPkRhIENoYXQ8L2gxPiIsIjxjaGF0PjwvY2hhdD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQSx3RUFBSTthQUFBOzs7b0JDQUo7TUFBQTthQUFBOzs7OyJ9
