"use strict";
/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
/* tslint:disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.styles = ['.chat-actionbar[_ngcontent-%COMP%] {\r\n    background: rgb(0, 51, 102);\r\n    position: absolute;\r\n    bottom: 0;\r\n    width: 100%;\r\n    padding: 3px 0px 3px 0px;\r\n    z-index: 30;\r\n}\r\n\r\n.chat-actionbar[_ngcontent-%COMP%]   .input-message[_ngcontent-%COMP%] {\r\n    border: none;\r\n    width: 85%;\r\n    display: block;\r\n    float: left;\r\n}\r\n\r\n.chat-actionbar[_ngcontent-%COMP%]   .input-message[_ngcontent-%COMP%]   input[_ngcontent-%COMP%] {\r\n    border: 0;\r\n    font-size: 1em;\r\n    width: 100%;\r\n    display: block;\r\n    padding: 10px;\r\n}\r\n\r\n.chat-actionbar[_ngcontent-%COMP%]   .btn-send[_ngcontent-%COMP%] {\r\n    font-size: 1em;\r\n    width: 15%;\r\n    background: rgb(255, 153, 0);\r\n    border: none;\r\n    display: block;\r\n    float: left;\r\n}\r\n\r\n.chat-actionbar[_ngcontent-%COMP%]   .btn-send[_ngcontent-%COMP%]   button[_ngcontent-%COMP%] {\r\n    font-size: 1em;\r\n    width: 100%;\r\n    background: rgb(255, 153, 0);\r\n    border: none;\r\n    display: block;\r\n    padding: 10px;\r\n}\r\n\r\n.chat-actionbar[_ngcontent-%COMP%]   .btn-send[_ngcontent-%COMP%]   button[_ngcontent-%COMP%]:active {\r\n    background: rgb(225, 123, 0);\r\n}'];
//# sourceMappingURL=chat-actionbar.component.css.shim.ngstyle.js.map