/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.chat-messages[_ngcontent-%COMP%] {\n    margin: 0;\n    padding: 0;\n    width: calc(85% - 6px);\n    position: absolute;\n    padding-right: 3px;\n    height: calc(100vh - 1.75em - 20px);\n    overflow-y: auto;\n}\n\n.chat-messages[_ngcontent-%COMP%]   ul[_ngcontent-%COMP%] {\n    list-style-type: none;\n    position: relative;\n    width: 100%;\n}\n\n.chat-messages[_ngcontent-%COMP%]   ul[_ngcontent-%COMP%]   li[_ngcontent-%COMP%] {\n    padding: 5px 10px;\n}\n\n.chat-messages[_ngcontent-%COMP%]   ul[_ngcontent-%COMP%]   li.bold[_ngcontent-%COMP%] {\n    font-weight: bold;\n}\n\n.chat-messages[_ngcontent-%COMP%]   ul[_ngcontent-%COMP%]   li[_ngcontent-%COMP%]:nth-child(odd) {\n    background: rgb(187, 187, 187);\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvUHJlc2NoZXJGYS9Qcm9qZWt0ZS9ZQUNoYXQvd2ViY2xpZW50L3NyYy9jaGF0L2NoYXQtbWVzc2FnZXMuY29tcG9uZW50LmNzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy9QcmVzY2hlckZhL1Byb2pla3RlL1lBQ2hhdC93ZWJjbGllbnQvc3JjL2NoYXQvY2hhdC1tZXNzYWdlcy5jb21wb25lbnQuY3NzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
