"use strict";
/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
/* tslint:disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.styles = ['.chat-messages[_ngcontent-%COMP%] {\n    margin: 0;\n    padding: 0;\n    width: calc(85% - 6px);\n    position: absolute;\n    padding-right: 3px;\n    height: calc(100vh - 1.75em - 20px);\n    overflow-y: auto;\n}\n\n.chat-messages[_ngcontent-%COMP%]   ul[_ngcontent-%COMP%] {\n    list-style-type: none;\n    position: relative;\n    width: 100%;\n}\n\n.chat-messages[_ngcontent-%COMP%]   ul[_ngcontent-%COMP%]   li[_ngcontent-%COMP%] {\n    padding: 5px 10px;\n}\n\n.chat-messages[_ngcontent-%COMP%]   ul[_ngcontent-%COMP%]   li.bold[_ngcontent-%COMP%] {\n    font-weight: bold;\n}\n\n.chat-messages[_ngcontent-%COMP%]   ul[_ngcontent-%COMP%]   li[_ngcontent-%COMP%]:nth-child(odd) {\n    background: rgb(187, 187, 187);\n}'];
//# sourceMappingURL=chat-messages.component.css.shim.ngstyle.js.map