/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.chat-actionbar[_ngcontent-%COMP%] {\r\n    background: rgb(0, 51, 102);\r\n    position: absolute;\r\n    bottom: 0;\r\n    width: 100%;\r\n    padding: 3px 0px 3px 0px;\r\n    z-index: 30;\r\n}\r\n\r\n.chat-actionbar[_ngcontent-%COMP%]   .input-message[_ngcontent-%COMP%] {\r\n    border: none;\r\n    width: 85%;\r\n    display: block;\r\n    float: left;\r\n}\r\n\r\n.chat-actionbar[_ngcontent-%COMP%]   .input-message[_ngcontent-%COMP%]   input[_ngcontent-%COMP%] {\r\n    border: 0;\r\n    font-size: 1em;\r\n    width: 100%;\r\n    display: block;\r\n    padding: 10px;\r\n}\r\n\r\n.chat-actionbar[_ngcontent-%COMP%]   .btn-send[_ngcontent-%COMP%] {\r\n    font-size: 1em;\r\n    width: 15%;\r\n    background: rgb(255, 153, 0);\r\n    border: none;\r\n    display: block;\r\n    float: left;\r\n}\r\n\r\n.chat-actionbar[_ngcontent-%COMP%]   .btn-send[_ngcontent-%COMP%]   button[_ngcontent-%COMP%] {\r\n    font-size: 1em;\r\n    width: 100%;\r\n    background: rgb(255, 153, 0);\r\n    border: none;\r\n    display: block;\r\n    padding: 10px;\r\n}\r\n\r\n.chat-actionbar[_ngcontent-%COMP%]   .btn-send[_ngcontent-%COMP%]   button[_ngcontent-%COMP%]:active {\r\n    background: rgb(225, 123, 0);\r\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRTovUHJvamVrdGUvWUFDaGF0L3dlYmNsaWVudC9zcmMvY2hhdC9jaGF0LWFjdGlvbmJhci5jb21wb25lbnQuY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0U6L1Byb2pla3RlL1lBQ2hhdC93ZWJjbGllbnQvc3JjL2NoYXQvY2hhdC1hY3Rpb25iYXIuY29tcG9uZW50LmNzcyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
