"use strict";
/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
/* tslint:disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.styles = ['.chat-messages[_ngcontent-%COMP%] {\r\n    margin: 0;\r\n    padding: 0;\r\n    width: calc(85% - 6px);\r\n    position: absolute;\r\n    padding-right: 3px;\r\n    height: calc(100vh - 1.75em - 20px);\r\n    overflow-y: auto;\r\n}\r\n\r\n.chat-messages[_ngcontent-%COMP%]   ul[_ngcontent-%COMP%] {\r\n    list-style-type: none;\r\n    position: relative;\r\n    width: 100%;\r\n}\r\n\r\n.chat-messages[_ngcontent-%COMP%]   ul[_ngcontent-%COMP%]   li[_ngcontent-%COMP%] {\r\n    padding: 5px 10px;\r\n}\r\n\r\n.chat-messages[_ngcontent-%COMP%]   ul[_ngcontent-%COMP%]   li[_ngcontent-%COMP%]:nth-child(odd) {\r\n    background: rgb(187, 187, 187);\r\n}'];
//# sourceMappingURL=chat-messages.component.css.shim.ngstyle.js.map